//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFrequencyApp.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFrequencyApp.Localisation.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting application.
        /// </summary>
        internal static string ApplicationStart {
            get {
                return ResourceManager.GetString("ApplicationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting Windows-1252 Encoding.
        /// </summary>
        internal static string EncodingError {
            get {
                return ResourceManager.GetString("EncodingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILURE!.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file does not exist.
        /// </summary>
        internal static string InputFileNotExist {
            get {
                return ResourceManager.GetString("InputFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file has incorrect characters.
        /// </summary>
        internal static string InputIncorrectCharacters {
            get {
                return ResourceManager.GetString("InputIncorrectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input path:.
        /// </summary>
        internal static string InputPathLabel {
            get {
                return ResourceManager.GetString("InputPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, see the logs for more details.
        /// </summary>
        internal static string InternalErrorDetails {
            get {
                return ResourceManager.GetString("InternalErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They must have two command line arguments.
        /// </summary>
        internal static string NeedTwoArguments {
            get {
                return ResourceManager.GetString("NeedTwoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file&apos;s directory does not exist.
        /// </summary>
        internal static string OutputDirectoryNotExist {
            get {
                return ResourceManager.GetString("OutputDirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file has incorrect characters.
        /// </summary>
        internal static string OutputIncorrectCharacters {
            get {
                return ResourceManager.GetString("OutputIncorrectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file path is an existing directory.
        /// </summary>
        internal static string OutputPathIsAlreadyADirectory {
            get {
                return ResourceManager.GetString("OutputPathIsAlreadyADirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output path:.
        /// </summary>
        internal static string OutputPathLabel {
            get {
                return ResourceManager.GetString("OutputPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while reading file.
        /// </summary>
        internal static string ReadingFailed {
            get {
                return ResourceManager.GetString("ReadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading input file failed, see the logs for more details.
        /// </summary>
        internal static string ReadingFailedDetails {
            get {
                return ResourceManager.GetString("ReadingFailedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while writing file.
        /// </summary>
        internal static string WritingFailed {
            get {
                return ResourceManager.GetString("WritingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing in output file failed, see the logs for more details.
        /// </summary>
        internal static string WritingFailedDetails {
            get {
                return ResourceManager.GetString("WritingFailedDetails", resourceCulture);
            }
        }
    }
}
